name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build for ${{ matrix.goos }}/${{ matrix.goarch }}
      run: |
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o markdown-viewer-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: markdown-viewer-${{ matrix.goos }}-${{ matrix.goarch }}
        path: markdown-viewer-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        path: .

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          markdown-viewer-linux-amd64
          markdown-viewer-linux-arm64
          markdown-viewer-windows-amd64.exe
          markdown-viewer-windows-arm64.exe
          markdown-viewer-darwin-amd64
          markdown-viewer-darwin-arm64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
